# keycloak.yaml: Defines the Keycloak identity service
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
type: Opaque
data:
  # IMPORTANT: These are placeholder values.
  # You MUST replace them with your own base64 encoded secrets.
  # Example: echo 'my-super-secret-password' | base64
  KEYCLOAK_ADMIN: YWRtaW4= # Default: admin
  KEYCLOAK_ADMIN_PASSWORD: YWRtaW4= # Default: admin
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-svc
spec:
  ports:
  - port: 8080
  selector:
    app: keycloak
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
        image: quay.io/keycloak/keycloak:26.3
        args: ["start-dev"]
        env:
        - name: KC_BOOTSTRAP_ADMIN_USERNAME
          valueFrom:
            secretKeyRef:
              name: keycloak-secret
              key: KEYCLOAK_ADMIN
        - name: KC_BOOTSTRAP_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: keycloak-secret
              key: KEYCLOAK_ADMIN_PASSWORD
        - name: KC_DB
          value: "dev-file" # Use a file-based store for dev. For prod, use KC_DB=postgres
        ports:
        - name: http
          containerPort: 8080
#        readinessProbe:
#          httpGet:
#            path: /health/ready
#            port: 9000
#          initialDelaySeconds: 30
#          periodSeconds: 10
